### ISSUE TITLE
Buttons no longer hold state

### ISSUE THREAD

**Issue by superhu4** [getgrav/grav-plugin-form#406] opened 2020-02-06 16:15 UTC
After updating from 4.0.1 to 4.0.2 on a clean install of Grav, buttons no longer holder their state.

For example, after creating a page and then going to Advanced > Overrides, disabling Routable, Caching, Visible, or Debugger will not hold. They will go back to their default after the next edit.

![Screen Shot 2020-02-06 at 11 11 19 AM](https://user-images.githubusercontent.com/40218684/73955780-e5dc3480-48d1-11ea-91af-8ed7754b6804.png)

**Comment by mahagr** [comment] 2020-02-07 08:39
Could be Grav update, too. I've been trying to fix another bug and just found an issue in my fix yesterday.

**Comment by pospiemi** [comment] 2020-03-01 17:32
Downgrading Form from 4.0.4 to 4.0.1: The configuration is shown correctly with checked checkboxes and saved as expected.
![v4 0 1](https://user-images.githubusercontent.com/11717132/75629641-e8d1f880-5be3-11ea-9bde-6fa0c4ffdc1e.png)

Using 4.0.2: 
![v4 0 2](https://user-images.githubusercontent.com/11717132/75629669-2040a500-5be4-11ea-99ff-e2fa57df155f.png)
Config is shown correctly "Disabled", but due to the unchecked checkboxes, the configuration is lost once the page is saved (e.g. "cache_enable: false" and "visible: false" is removed from frontmatter)

Reverting 5d720df worked for me.
(Grav 1.6.21/Admin 1.9.12/Form 4.0.4)

@mahagr IMHO this should to be fixed soon.

**Comment by rhukster** [comment] 2020-03-01 23:03
I can confirm that putting the:

```
{% set value = value ?? field.default %}
{% set value = (value is same as(false) ? 0 : value) %}
```

outside of the input block does work in Grav 1.6/Admin 1.9.

however, with things as they are and just:

```
% set value = (value is same as(false) ? 0 : value) %}
```

Inside the input block, works in Grav 1.7rc6/Admin 1.10r6.

Further confusing the issue, is the fact that no matter which of these I try, they don't seem to work in Grav 1.7/Admin 1.7 latest github versions.. So i'm completely confused.  Something else is at play.  @mahagr let's discuss tomorrow.

**Comment by mahagr** [comment] 2020-03-02 08:56
Looks like the same issue as in here: https://github.com/getgrav/grav/issues/2840

**Comment by mahagr** [comment] 2020-03-02 19:56
Should be now fixed. Needs grav + admin + form updates.

**Comment by mahagr** [comment] 2020-03-02 19:59
@rhukster FYI: for this issue the issue was that `false is not empty` resulted false, making the toggle to turn off. Not sure why the check was there because of if the value is set, toggle should always be on regardless of the value.

**Closed** 2020-03-19 18:17 UTC
Labels: bug
