### ISSUE TITLE
file upload (dropzone) with validate: required can not be submitted

### ISSUE THREAD

**Issue by stephan-strate** [getgrav/grav-plugin-form#499] opened 2021-02-18 09:38 UTC
Creating a file upload (frontend form) with `required: true` leads to form being not submittable (with file selected and without). Error in console: `An invalid form control with name='' is not focusable.`. Tried to investigate it myself, but did not find any documentation on making dropzone fields required. In [Grav documentation](https://learn.getgrav.org/17/forms/forms/fields-available#file-field) it is listed as a valid common attribute. It also marks the field as required using `*`.

Example code:
```yaml
form:
  name: testform
  buttons:
    submit:
      value: Send
      type: submit
  fields:
    -
      label: File
      name: myfile
      type: file
      destination: user/data/form
      accept:
        - '*'
      multiple: false
      filesize: 10
      avoid_overwriting: true
      random_name: false
      validate:
        required: true
  process:
    save:
      body: '{% include ''forms/data.txt.twig'' %}'
      operations: add
      filename: form.txt
```

Versions:
Grav: v1.7.6
Form: v5.0.0
(did not work in version before as well)

**Comment by mahagr** [comment] 2021-02-18 10:09
Yeah, required doesn't work with any file fields.

**Comment by stephan-strate** [comment] 2021-02-18 10:27
> Yeah, required doesn't work with any file fields.

Thanks for confirmation. Do you think this is something that can be fixed? Just want to ask before I dig into it.

**Comment by mahagr** [comment] 2021-02-22 17:08
It is somewhat tricky to fix as the form is also used to save existing data. I think it is possible to get it working, though.

**Comment by crinavar** [comment] 2021-05-30 21:30
Hi,
any plans on fixing this? having the same problem

**Comment by hughbris** [comment] 2021-12-14 03:29
Duplicate of #418

**Comment by mahagr** [comment] 2021-12-14 16:45
Closing as duplicate.

**Closed by mahagr** 2021-12-14 16:45 UTC
Labels: bug
