### ISSUE TITLE
Wrong action on multi-language site

### ISSUE THREAD

**Issue by lufog** [getgrav/grav-plugin-form#358] opened 2019-07-09 16:42 UTC
More details:
https://github.com/getgrav/grav-plugin-login/issues/216#issuecomment-509705626

**Comment by mahagr** [comment] 2019-07-09 18:10
Duplicate of https://github.com/getgrav/grav-plugin-form/issues/355

And it's already fixed. Thanks for reporting it, though!

**Closed by mahagr** 2019-07-09 18:10 UTC
Labels: duplicate
